# Generated by Django 4.0.2 on 2022-03-03 16:52

import buff_file.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buff_file', '0002_remove_file_path_file_type_file_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(null=True, upload_to=buff_file.models.user_directory_path),
        ),
    ]
