# Generated by Django 4.0.2 on 2022-02-28 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='表格标题')),
                ('header', models.CharField(blank=True, default='', max_length=255, verbose_name='表格表头')),
                ('body', models.TextField(verbose_name='表格内容')),
                ('user_id', models.CharField(blank=True, default='', max_length=255, verbose_name='表格所属用户')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
    ]
