# Generated by Django 4.0.2 on 2022-03-05 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buff_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chart',
            name='user_id',
        ),
        migrations.AddField(
            model_name='chart',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chart',
            name='body',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='chart',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='chart',
            name='header',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='chart',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='chart',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
