# Generated by Django 4.0.2 on 2022-02-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buff_user', '0002_user_gender_user_image_user_nick_name_user_user_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('男', 'Male'), ('女', 'Female'), ('未知', 'Unknown')], default='未知', max_length=8),
        ),
    ]
