# Generated by Django 4.0.2 on 2022-03-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buff_user', '0004_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('男', 'Male'), ('女', 'Female'), ('未知', 'Unknown')], default='未知', max_length=8),
        ),
    ]
