# Generated by Django 4.0.2 on 2022-03-02 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buff_user', '0006_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='static/images/default.png', upload_to='static/images/'),
        ),
    ]
